In [11]:
import numpy as np

In [12]:
n = int(input())

In [13]:
null_array = np.zeros(n, dtype=int)
print(null_array)

[0 0 0 0 0]


In [14]:
start_number = int(input())
end_number = int(input())

consecutive_array = np.arange(start_number, end_number + 1)

print(consecutive_array)

[5]


In [15]:

N = int(input())
identity_matrix = np.identity(N, dtype=int)
print(identity_matrix)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [16]:
start = float(input())
stop = float(input())
N = int(input())

result_array = np.linspace(start, stop, N)
print(result_array)

[5. 5. 5. 5. 5.]
